// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_text.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_geometry } from "./lens_overlay_geometry_pb.js";

/**
 * Describes the file lens_overlay_text.proto.
 */
export const file_lens_overlay_text = /*@__PURE__*/
  fileDesc("ChdsZW5zX292ZXJsYXlfdGV4dC5wcm90bxIEbGVucyJHCgRUZXh0EiUKC3RleHRfbGF5b3V0GAEgASgLMhAubGVucy5UZXh0TGF5b3V0EhgKEGNvbnRlbnRfbGFuZ3VhZ2UYAiABKAkimgUKClRleHRMYXlvdXQSLgoKcGFyYWdyYXBocxgBIAMoCzIaLmxlbnMuVGV4dExheW91dC5QYXJhZ3JhcGgawAIKBFdvcmQSJgoCaWQYASABKAsyGi5sZW5zLlRleHRFbnRpdHlJZGVudGlmaWVyEhIKCnBsYWluX3RleHQYAiABKAkSGwoOdGV4dF9zZXBhcmF0b3IYAyABKAlIAIgBARIgCghnZW9tZXRyeRgEIAEoCzIOLmxlbnMuR2VvbWV0cnkSKAoEdHlwZRgFIAEoDjIaLmxlbnMuVGV4dExheW91dC5Xb3JkLlR5cGUSPwoQZm9ybXVsYV9tZXRhZGF0YRgGIAEoCzIlLmxlbnMuVGV4dExheW91dC5Xb3JkLkZvcm11bGFNZXRhZGF0YRogCg9Gb3JtdWxhTWV0YWRhdGESDQoFbGF0ZXgYASABKAkiHQoEVHlwZRIICgRURVhUEAASCwoHRk9STVVMQRABQhEKD190ZXh0X3NlcGFyYXRvchpOCgRMaW5lEiQKBXdvcmRzGAEgAygLMhUubGVucy5UZXh0TGF5b3V0LldvcmQSIAoIZ2VvbWV0cnkYAiABKAsyDi5sZW5zLkdlb21ldHJ5GsgBCglQYXJhZ3JhcGgSJgoCaWQYASABKAsyGi5sZW5zLlRleHRFbnRpdHlJZGVudGlmaWVyEiQKBWxpbmVzGAIgAygLMhUubGVucy5UZXh0TGF5b3V0LkxpbmUSIAoIZ2VvbWV0cnkYAyABKAsyDi5sZW5zLkdlb21ldHJ5EjEKEXdyaXRpbmdfZGlyZWN0aW9uGAQgASgOMhYubGVucy5Xcml0aW5nRGlyZWN0aW9uEhgKEGNvbnRlbnRfbGFuZ3VhZ2UYBSABKAkiIgoUVGV4dEVudGl0eUlkZW50aWZpZXISCgoCaWQYASABKAMqiQEKEFdyaXRpbmdEaXJlY3Rpb24SKwonREVGQVVMVF9XUklUSU5HX0RJUkVDVElPTl9MRUZUX1RPX1JJR0hUEAASIwofV1JJVElOR19ESVJFQ1RJT05fUklHSFRfVE9fTEVGVBABEiMKH1dSSVRJTkdfRElSRUNUSU9OX1RPUF9UT19CT1RUT00QAipMCglBbGlnbm1lbnQSGAoUREVGQVVMVF9MRUZUX0FMSUdORUQQABIRCg1SSUdIVF9BTElHTkVEEAESEgoOQ0VOVEVSX0FMSUdORUQQAmIGcHJvdG8z", [file_lens_overlay_geometry]);

/**
 * Describes the message lens.Text.
 * Use `create(TextSchema)` to create a new message.
 */
export const TextSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text, 0);

/**
 * Describes the message lens.TextLayout.
 * Use `create(TextLayoutSchema)` to create a new message.
 */
export const TextLayoutSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text, 1);

/**
 * Describes the message lens.TextLayout.Word.
 * Use `create(TextLayout_WordSchema)` to create a new message.
 */
export const TextLayout_WordSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text, 1, 0);

/**
 * Describes the message lens.TextLayout.Word.FormulaMetadata.
 * Use `create(TextLayout_Word_FormulaMetadataSchema)` to create a new message.
 */
export const TextLayout_Word_FormulaMetadataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text, 1, 0, 0);

/**
 * Describes the enum lens.TextLayout.Word.Type.
 */
export const TextLayout_Word_TypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_text, 1, 0, 0);

/**
 * @generated from enum lens.TextLayout.Word.Type
 */
export const TextLayout_Word_Type = /*@__PURE__*/
  tsEnum(TextLayout_Word_TypeSchema);

/**
 * Describes the message lens.TextLayout.Line.
 * Use `create(TextLayout_LineSchema)` to create a new message.
 */
export const TextLayout_LineSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text, 1, 1);

/**
 * Describes the message lens.TextLayout.Paragraph.
 * Use `create(TextLayout_ParagraphSchema)` to create a new message.
 */
export const TextLayout_ParagraphSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text, 1, 2);

/**
 * Describes the message lens.TextEntityIdentifier.
 * Use `create(TextEntityIdentifierSchema)` to create a new message.
 */
export const TextEntityIdentifierSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text, 2);

/**
 * Describes the enum lens.WritingDirection.
 */
export const WritingDirectionSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_text, 0);

/**
 * @generated from enum lens.WritingDirection
 */
export const WritingDirection = /*@__PURE__*/
  tsEnum(WritingDirectionSchema);

/**
 * Describes the enum lens.Alignment.
 */
export const AlignmentSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_text, 1);

/**
 * @generated from enum lens.Alignment
 */
export const Alignment = /*@__PURE__*/
  tsEnum(AlignmentSchema);

