// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_deep_gleam_data.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_text } from "./lens_overlay_text_pb.js";

/**
 * Describes the file lens_overlay_deep_gleam_data.proto.
 */
export const file_lens_overlay_deep_gleam_data = /*@__PURE__*/
  fileDesc("CiJsZW5zX292ZXJsYXlfZGVlcF9nbGVhbV9kYXRhLnByb3RvEgRsZW5zImoKDURlZXBHbGVhbURhdGESLAoLdHJhbnNsYXRpb24YCiABKAsyFS5sZW5zLlRyYW5zbGF0aW9uRGF0YUgAEhgKEHZpc3VhbF9vYmplY3RfaWQYCyADKAlCEQoPcmVuZGVyaW5nX29uZW9mIr0JCg9UcmFuc2xhdGlvbkRhdGESLAoGc3RhdHVzGAEgASgLMhwubGVucy5UcmFuc2xhdGlvbkRhdGEuU3RhdHVzEhcKD3RhcmdldF9sYW5ndWFnZRgCIAEoCRIXCg9zb3VyY2VfbGFuZ3VhZ2UYAyABKAkSEwoLdHJhbnNsYXRpb24YBCABKAkSKAoEbGluZRgFIAMoCzIaLmxlbnMuVHJhbnNsYXRpb25EYXRhLkxpbmUSMQoRd3JpdGluZ19kaXJlY3Rpb24YByABKA4yFi5sZW5zLldyaXRpbmdEaXJlY3Rpb24SIgoJYWxpZ25tZW50GAggASgOMg8ubGVucy5BbGlnbm1lbnQSEQoJanVzdGlmaWVkGAkgASgIGpcCCgZTdGF0dXMSLwoEY29kZRgBIAEoDjIhLmxlbnMuVHJhbnNsYXRpb25EYXRhLlN0YXR1cy5Db2RlItsBCgRDb2RlEgsKB1VOS05PV04QABILCgdTVUNDRVNTEAESEAoMU0VSVkVSX0VSUk9SEAISHQoZVU5TVVBQT1JURURfTEFOR1VBR0VfUEFJUhADEhEKDVNBTUVfTEFOR1VBR0UQBBIbChdVTktOT1dOX1NPVVJDRV9MQU5HVUFHRRAFEhMKD0lOVkFMSURfUkVRVUVTVBAGEhUKEURFQURMSU5FX0VYQ0VFREVEEAcSFQoRRU1QVFlfVFJBTlNMQVRJT04QCBIVChFOT19PUF9UUkFOU0xBVElPThAJGkEKCVRleHRTdHlsZRISCgp0ZXh0X2NvbG9yGAEgASgNEiAKGGJhY2tncm91bmRfcHJpbWFyeV9jb2xvchgCIAEoDRrRAgoTQmFja2dyb3VuZEltYWdlRGF0YRIYChBiYWNrZ3JvdW5kX2ltYWdlGAEgASgMEhMKC2ltYWdlX3dpZHRoGAIgASgFEhQKDGltYWdlX2hlaWdodBgDIAEoBRIYChB2ZXJ0aWNhbF9wYWRkaW5nGAQgASgCEhoKEmhvcml6b250YWxfcGFkZGluZxgFIAEoAhJJCgtmaWxlX2Zvcm1hdBgGIAEoDjI0LmxlbnMuVHJhbnNsYXRpb25EYXRhLkJhY2tncm91bmRJbWFnZURhdGEuRmlsZUZvcm1hdBIRCgl0ZXh0X21hc2sYByABKAwiYQoKRmlsZUZvcm1hdBILCgdVTktOT1dOEAASEgoOUkFXX0JZVEVTX1JHQkEQARIMCghQTkdfUkdCQRACEg0KCVdFQlBfUkdCQRADEhUKEUpQRUdfUkdCX1BOR19NQVNLEAQa7wEKBExpbmUSDQoFc3RhcnQYASABKAUSCwoDZW5kGAIgASgFEi4KBXN0eWxlGAMgASgLMh8ubGVucy5UcmFuc2xhdGlvbkRhdGEuVGV4dFN0eWxlEi0KBHdvcmQYBSADKAsyHy5sZW5zLlRyYW5zbGF0aW9uRGF0YS5MaW5lLldvcmQSSAoVYmFja2dyb3VuZF9pbWFnZV9kYXRhGAkgASgLMikubGVucy5UcmFuc2xhdGlvbkRhdGEuQmFja2dyb3VuZEltYWdlRGF0YRoiCgRXb3JkEg0KBXN0YXJ0GAEgASgFEgsKA2VuZBgCIAEoBWIGcHJvdG8z", [file_lens_overlay_text]);

/**
 * Describes the message lens.DeepGleamData.
 * Use `create(DeepGleamDataSchema)` to create a new message.
 */
export const DeepGleamDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_deep_gleam_data, 0);

/**
 * Describes the message lens.TranslationData.
 * Use `create(TranslationDataSchema)` to create a new message.
 */
export const TranslationDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_deep_gleam_data, 1);

/**
 * Describes the message lens.TranslationData.Status.
 * Use `create(TranslationData_StatusSchema)` to create a new message.
 */
export const TranslationData_StatusSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_deep_gleam_data, 1, 0);

/**
 * Describes the enum lens.TranslationData.Status.Code.
 */
export const TranslationData_Status_CodeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_deep_gleam_data, 1, 0, 0);

/**
 * @generated from enum lens.TranslationData.Status.Code
 */
export const TranslationData_Status_Code = /*@__PURE__*/
  tsEnum(TranslationData_Status_CodeSchema);

/**
 * Describes the message lens.TranslationData.TextStyle.
 * Use `create(TranslationData_TextStyleSchema)` to create a new message.
 */
export const TranslationData_TextStyleSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_deep_gleam_data, 1, 1);

/**
 * Describes the message lens.TranslationData.BackgroundImageData.
 * Use `create(TranslationData_BackgroundImageDataSchema)` to create a new message.
 */
export const TranslationData_BackgroundImageDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_deep_gleam_data, 1, 2);

/**
 * Describes the enum lens.TranslationData.BackgroundImageData.FileFormat.
 */
export const TranslationData_BackgroundImageData_FileFormatSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_deep_gleam_data, 1, 2, 0);

/**
 * @generated from enum lens.TranslationData.BackgroundImageData.FileFormat
 */
export const TranslationData_BackgroundImageData_FileFormat = /*@__PURE__*/
  tsEnum(TranslationData_BackgroundImageData_FileFormatSchema);

/**
 * Describes the message lens.TranslationData.Line.
 * Use `create(TranslationData_LineSchema)` to create a new message.
 */
export const TranslationData_LineSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_deep_gleam_data, 1, 3);

/**
 * Describes the message lens.TranslationData.Line.Word.
 * Use `create(TranslationData_Line_WordSchema)` to create a new message.
 */
export const TranslationData_Line_WordSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_deep_gleam_data, 1, 3, 0);

