// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_routing_info.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_routing_info.proto.
 */
export const file_lens_overlay_routing_info = /*@__PURE__*/
  fileDesc("Ch9sZW5zX292ZXJsYXlfcm91dGluZ19pbmZvLnByb3RvEgRsZW5zIlwKFkxlbnNPdmVybGF5Um91dGluZ0luZm8SFgoOc2VydmVyX2FkZHJlc3MYASABKAkSFAoMY2VsbF9hZGRyZXNzGAMgASgJEhQKDGJsYWRlX3RhcmdldBgCIAEoCWIGcHJvdG8z");

/**
 * Describes the message lens.LensOverlayRoutingInfo.
 * Use `create(LensOverlayRoutingInfoSchema)` to create a new message.
 */
export const LensOverlayRoutingInfoSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_routing_info, 0);

