// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_document.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_document.proto.
 */
export const file_lens_overlay_document = /*@__PURE__*/
  fileDesc("ChtsZW5zX292ZXJsYXlfZG9jdW1lbnQucHJvdG8SBGxlbnMiMAoTTGVuc092ZXJsYXlEb2N1bWVudBIZCgVwYWdlcxgBIAMoCzIKLmxlbnMuUGFnZSIyCgRQYWdlEhMKC3BhZ2VfbnVtYmVyGAEgASgFEhUKDXRleHRfc2VnbWVudHMYBCADKAliBnByb3RvMw");

/**
 * Describes the message lens.LensOverlayDocument.
 * Use `create(LensOverlayDocumentSchema)` to create a new message.
 */
export const LensOverlayDocumentSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_document, 0);

/**
 * Describes the message lens.Page.
 * Use `create(PageSchema)` to create a new message.
 */
export const PageSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_document, 1);

