// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_translate_stickiness_signals.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_translate_stickiness_signals.proto.
 */
export const file_lens_overlay_translate_stickiness_signals = /*@__PURE__*/
  fileDesc("Ci9sZW5zX292ZXJsYXlfdHJhbnNsYXRlX3N0aWNraW5lc3Nfc2lnbmFscy5wcm90bxIEbGVucyJIChpUcmFuc2xhdGVTdGlja2luZXNzU2lnbmFscxIqCiJ0cmFuc2xhdGVfc3VwcHJlc3NfZWNob19mb3Jfc3RpY2t5GAEgASgIYgZwcm90bzM");

/**
 * Describes the message lens.TranslateStickinessSignals.
 * Use `create(TranslateStickinessSignalsSchema)` to create a new message.
 */
export const TranslateStickinessSignalsSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_translate_stickiness_signals, 0);

