// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_video_context_input_params.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_video_context_input_params.proto.
 */
export const file_lens_overlay_video_context_input_params = /*@__PURE__*/
  fileDesc("Ci1sZW5zX292ZXJsYXlfdmlkZW9fY29udGV4dF9pbnB1dF9wYXJhbXMucHJvdG8SBGxlbnMiMQoiTGVuc092ZXJsYXlWaWRlb0NvbnRleHRJbnB1dFBhcmFtcxILCgN1cmwYASABKAliBnByb3RvMw");

/**
 * Describes the message lens.LensOverlayVideoContextInputParams.
 * Use `create(LensOverlayVideoContextInputParamsSchema)` to create a new message.
 */
export const LensOverlayVideoContextInputParamsSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_video_context_input_params, 0);

