// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_visual_search_interaction_data.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_geometry } from "./lens_overlay_geometry_pb.js";
import { file_lens_overlay_interaction_request_metadata } from "./lens_overlay_interaction_request_metadata_pb.js";
import { file_lens_overlay_visual_search_interaction_log_data } from "./lens_overlay_visual_search_interaction_log_data_pb.js";

/**
 * Describes the file lens_overlay_visual_search_interaction_data.proto.
 */
export const file_lens_overlay_visual_search_interaction_data = /*@__PURE__*/
  fileDesc("CjFsZW5zX292ZXJsYXlfdmlzdWFsX3NlYXJjaF9pbnRlcmFjdGlvbl9kYXRhLnByb3RvEgRsZW5zIvEBCiZMZW5zT3ZlcmxheVZpc3VhbFNlYXJjaEludGVyYWN0aW9uRGF0YRJKChBpbnRlcmFjdGlvbl90eXBlGAEgASgOMjAubGVucy5MZW5zT3ZlcmxheUludGVyYWN0aW9uUmVxdWVzdE1ldGFkYXRhLlR5cGUSJQoLem9vbWVkX2Nyb3AYByABKAsyEC5sZW5zLlpvb21lZENyb3ASEQoJb2JqZWN0X2lkGAMgASgJEkEKCGxvZ19kYXRhGAUgASgLMi8ubGVucy5MZW5zT3ZlcmxheVZpc3VhbFNlYXJjaEludGVyYWN0aW9uTG9nRGF0YWIGcHJvdG8z", [file_lens_overlay_geometry, file_lens_overlay_interaction_request_metadata, file_lens_overlay_visual_search_interaction_log_data]);

/**
 * Describes the message lens.LensOverlayVisualSearchInteractionData.
 * Use `create(LensOverlayVisualSearchInteractionDataSchema)` to create a new message.
 */
export const LensOverlayVisualSearchInteractionDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_visual_search_interaction_data, 0);

