// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_math_solver_query.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_math_solver_query.proto.
 */
export const file_lens_overlay_math_solver_query = /*@__PURE__*/
  fileDesc("CiRsZW5zX292ZXJsYXlfbWF0aF9zb2x2ZXJfcXVlcnkucHJvdG8SBGxlbnMiLgoPTWF0aFNvbHZlclF1ZXJ5EhsKE21hdGhfaW5wdXRfZXF1YXRpb24YAyABKAliBnByb3RvMw");

/**
 * Describes the message lens.MathSolverQuery.
 * Use `create(MathSolverQuerySchema)` to create a new message.
 */
export const MathSolverQuerySchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_math_solver_query, 0);

