// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_message_set.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_knowledge_query } from "./lens_overlay_knowledge_query_pb.js";

/**
 * Describes the file lens_overlay_message_set.proto.
 */
export const file_lens_overlay_message_set = /*@__PURE__*/
  fileDesc("Ch5sZW5zX292ZXJsYXlfbWVzc2FnZV9zZXQucHJvdG8SBGxlbnMiOwoKTWVzc2FnZVNldBItChVtZXNzYWdlX3NldF9leHRlbnNpb24Y6fjeEyABKAsyCy5sZW5zLlF1ZXJ5YgZwcm90bzM", [file_lens_overlay_knowledge_query]);

/**
 * Describes the message lens.MessageSet.
 * Use `create(MessageSetSchema)` to create a new message.
 */
export const MessageSetSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_message_set, 0);

