// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_knowledge_query.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_knowledge_intent_query } from "./lens_overlay_knowledge_intent_query_pb.js";

/**
 * Describes the file lens_overlay_knowledge_query.proto.
 */
export const file_lens_overlay_knowledge_query = /*@__PURE__*/
  fileDesc("CiJsZW5zX292ZXJsYXlfa25vd2xlZGdlX3F1ZXJ5LnByb3RvEgRsZW5zIjQKBVF1ZXJ5EisKDGludGVudF9xdWVyeRjClekaIAEoCzISLmxlbnMuRnVuY3Rpb25DYWxsYgZwcm90bzM", [file_lens_overlay_knowledge_intent_query]);

/**
 * Describes the message lens.Query.
 * Use `create(QuerySchema)` to create a new message.
 */
export const QuerySchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_knowledge_query, 0);

