// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_polygon.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_polygon.proto.
 */
export const file_lens_overlay_polygon = /*@__PURE__*/
  fileDesc("ChpsZW5zX292ZXJsYXlfcG9seWdvbi5wcm90bxIEbGVucyKOAgoHUG9seWdvbhIkCgZ2ZXJ0ZXgYASADKAsyFC5sZW5zLlBvbHlnb24uVmVydGV4EjUKD3ZlcnRleF9vcmRlcmluZxgCIAEoDjIcLmxlbnMuUG9seWdvbi5WZXJ0ZXhPcmRlcmluZxItCg9jb29yZGluYXRlX3R5cGUYAyABKA4yFC5sZW5zLkNvb3JkaW5hdGVUeXBlGh4KBlZlcnRleBIJCgF4GAEgASgCEgkKAXkYAiABKAIiVwoOVmVydGV4T3JkZXJpbmcSHwobVkVSVEVYX09SREVSSU5HX1VOU1BFQ0lGSUVEEAASDQoJQ0xPQ0tXSVNFEAESFQoRQ09VTlRFUl9DTE9DS1dJU0UQAipMCg5Db29yZGluYXRlVHlwZRIfChtDT09SRElOQVRFX1RZUEVfVU5TUEVDSUZJRUQQABIOCgpOT1JNQUxJWkVEEAESCQoFSU1BR0UQAmIGcHJvdG8z");

/**
 * Describes the message lens.Polygon.
 * Use `create(PolygonSchema)` to create a new message.
 */
export const PolygonSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_polygon, 0);

/**
 * Describes the message lens.Polygon.Vertex.
 * Use `create(Polygon_VertexSchema)` to create a new message.
 */
export const Polygon_VertexSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_polygon, 0, 0);

/**
 * Describes the enum lens.Polygon.VertexOrdering.
 */
export const Polygon_VertexOrderingSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_polygon, 0, 0);

/**
 * @generated from enum lens.Polygon.VertexOrdering
 */
export const Polygon_VertexOrdering = /*@__PURE__*/
  tsEnum(Polygon_VertexOrderingSchema);

/**
 * Describes the enum lens.CoordinateType.
 */
export const CoordinateTypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_polygon, 0);

/**
 * @generated from enum lens.CoordinateType
 */
export const CoordinateType = /*@__PURE__*/
  tsEnum(CoordinateTypeSchema);

