// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_request_type.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_request_type.proto.
 */
export const file_lens_overlay_request_type = /*@__PURE__*/
  fileDesc("Ch9sZW5zX292ZXJsYXlfcmVxdWVzdF90eXBlLnByb3RvEgRsZW5zKnsKC1JlcXVlc3RUeXBlEhgKFFJFUVVFU1RfVFlQRV9ERUZBVUxUEAASFAoQUkVRVUVTVF9UWVBFX1BERhABEiIKHlJFUVVFU1RfVFlQRV9FQVJMWV9QQVJUSUFMX1BERhADEhgKFFJFUVVFU1RfVFlQRV9XRUJQQUdFEAJiBnByb3RvMw");

/**
 * Describes the enum lens.RequestType.
 */
export const RequestTypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_request_type, 0);

/**
 * @generated from enum lens.RequestType
 */
export const RequestType = /*@__PURE__*/
  tsEnum(RequestTypeSchema);

