// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_client_platform.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_client_platform.proto.
 */
export const file_lens_overlay_client_platform = /*@__PURE__*/
  fileDesc("CiJsZW5zX292ZXJsYXlfY2xpZW50X3BsYXRmb3JtLnByb3RvEgRsZW5zKlMKDkNsaWVudFBsYXRmb3JtEh8KG0NMSUVOVF9QTEFURk9STV9VTlNQRUNJRklFRBAAEiAKHENMSUVOVF9QTEFURk9STV9MRU5TX09WRVJMQVkQAmIGcHJvdG8z");

/**
 * Describes the enum lens.ClientPlatform.
 */
export const ClientPlatformSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_client_platform, 0);

/**
 * @generated from enum lens.ClientPlatform
 */
export const ClientPlatform = /*@__PURE__*/
  tsEnum(ClientPlatformSchema);

