// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_visual_search_interaction_log_data.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_client_platform } from "./lens_overlay_client_platform_pb.js";
import { file_lens_overlay_filters } from "./lens_overlay_filters_pb.js";
import { file_lens_overlay_selection_type } from "./lens_overlay_selection_type_pb.js";

/**
 * Describes the file lens_overlay_visual_search_interaction_log_data.proto.
 */
export const file_lens_overlay_visual_search_interaction_log_data = /*@__PURE__*/
  fileDesc("CjVsZW5zX292ZXJsYXlfdmlzdWFsX3NlYXJjaF9pbnRlcmFjdGlvbl9sb2dfZGF0YS5wcm90bxIEbGVucyLQAQopTGVuc092ZXJsYXlWaXN1YWxTZWFyY2hJbnRlcmFjdGlvbkxvZ0RhdGESJQoLZmlsdGVyX2RhdGEYASABKAsyEC5sZW5zLkZpbHRlckRhdGESNAoTdXNlcl9zZWxlY3Rpb25fZGF0YRgCIAEoCzIXLmxlbnMuVXNlclNlbGVjdGlvbkRhdGESFwoPaXNfcGFyZW50X3F1ZXJ5GAMgASgIEi0KD2NsaWVudF9wbGF0Zm9ybRgEIAEoDjIULmxlbnMuQ2xpZW50UGxhdGZvcm0iPgoKRmlsdGVyRGF0YRIwCgtmaWx0ZXJfdHlwZRgBIAEoDjIbLmxlbnMuTGVuc092ZXJsYXlGaWx0ZXJUeXBlIksKEVVzZXJTZWxlY3Rpb25EYXRhEjYKDnNlbGVjdGlvbl90eXBlGAEgASgOMh4ubGVucy5MZW5zT3ZlcmxheVNlbGVjdGlvblR5cGViBnByb3RvMw", [file_lens_overlay_client_platform, file_lens_overlay_filters, file_lens_overlay_selection_type]);

/**
 * Describes the message lens.LensOverlayVisualSearchInteractionLogData.
 * Use `create(LensOverlayVisualSearchInteractionLogDataSchema)` to create a new message.
 */
export const LensOverlayVisualSearchInteractionLogDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_visual_search_interaction_log_data, 0);

/**
 * Describes the message lens.FilterData.
 * Use `create(FilterDataSchema)` to create a new message.
 */
export const FilterDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_visual_search_interaction_log_data, 1);

/**
 * Describes the message lens.UserSelectionData.
 * Use `create(UserSelectionDataSchema)` to create a new message.
 */
export const UserSelectionDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_visual_search_interaction_log_data, 2);

