// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_image_data.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_geometry } from "./lens_overlay_geometry_pb.js";

/**
 * Describes the file lens_overlay_image_data.proto.
 */
export const file_lens_overlay_image_data = /*@__PURE__*/
  fileDesc("Ch1sZW5zX292ZXJsYXlfaW1hZ2VfZGF0YS5wcm90bxIEbGVucyKKAQoJSW1hZ2VEYXRhEiMKB3BheWxvYWQYASABKAsyEi5sZW5zLkltYWdlUGF5bG9hZBIrCg5pbWFnZV9tZXRhZGF0YRgDIAEoCzITLmxlbnMuSW1hZ2VNZXRhZGF0YRIrChNzaWduaWZpY2FudF9yZWdpb25zGAQgAygLMg4ubGVucy5HZW9tZXRyeSIjCgxJbWFnZVBheWxvYWQSEwoLaW1hZ2VfYnl0ZXMYASABKAwiLgoNSW1hZ2VNZXRhZGF0YRINCgV3aWR0aBgBIAEoBRIOCgZoZWlnaHQYAiABKAViBnByb3RvMw", [file_lens_overlay_geometry]);

/**
 * Describes the message lens.ImageData.
 * Use `create(ImageDataSchema)` to create a new message.
 */
export const ImageDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_image_data, 0);

/**
 * Describes the message lens.ImagePayload.
 * Use `create(ImagePayloadSchema)` to create a new message.
 */
export const ImagePayloadSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_image_data, 1);

/**
 * Describes the message lens.ImageMetadata.
 * Use `create(ImageMetadataSchema)` to create a new message.
 */
export const ImageMetadataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_image_data, 2);

