// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_stickiness_signals.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_math_solver_query } from "./lens_overlay_math_solver_query_pb.js";
import { file_lens_overlay_message_set } from "./lens_overlay_message_set_pb.js";

/**
 * Describes the file lens_overlay_stickiness_signals.proto.
 */
export const file_lens_overlay_stickiness_signals = /*@__PURE__*/
  fileDesc("CiVsZW5zX292ZXJsYXlfc3RpY2tpbmVzc19zaWduYWxzLnByb3RvEgRsZW5zIpECChFTdGlja2luZXNzU2lnbmFscxI8CgxpZF9uYW1lc3BhY2UYASABKA4yIS5sZW5zLlN0aWNraW5lc3NTaWduYWxzLk5hbWVzcGFjZUgAiAEBEigKDmludGVycHJldGF0aW9uGBwgASgLMhAubGVucy5NZXNzYWdlU2V0EkAKGWVkdWNhdGlvbl9pbnB1dF9leHRlbnNpb24YeSABKAsyHS5sZW5zLkVkdWNhdGlvbklucHV0RXh0ZW5zaW9uIkEKCU5hbWVzcGFjZRILCgdVTktOT1dOEAASEgoOVFJBTlNMQVRFX0xJVEUQOBITCg9FRFVDQVRJT05fSU5QVVQQT0IPCg1faWRfbmFtZXNwYWNlIksKF0VkdWNhdGlvbklucHV0RXh0ZW5zaW9uEjAKEW1hdGhfc29sdmVyX3F1ZXJ5GAEgASgLMhUubGVucy5NYXRoU29sdmVyUXVlcnliBnByb3RvMw", [file_lens_overlay_math_solver_query, file_lens_overlay_message_set]);

/**
 * Describes the message lens.StickinessSignals.
 * Use `create(StickinessSignalsSchema)` to create a new message.
 */
export const StickinessSignalsSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_stickiness_signals, 0);

/**
 * Describes the enum lens.StickinessSignals.Namespace.
 */
export const StickinessSignals_NamespaceSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_stickiness_signals, 0, 0);

/**
 * @generated from enum lens.StickinessSignals.Namespace
 */
export const StickinessSignals_Namespace = /*@__PURE__*/
  tsEnum(StickinessSignals_NamespaceSchema);

/**
 * Describes the message lens.EducationInputExtension.
 * Use `create(EducationInputExtensionSchema)` to create a new message.
 */
export const EducationInputExtensionSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_stickiness_signals, 1);

