// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_phase_latencies_metadata.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_phase_latencies_metadata.proto.
 */
export const file_lens_overlay_phase_latencies_metadata = /*@__PURE__*/
  fileDesc("CitsZW5zX292ZXJsYXlfcGhhc2VfbGF0ZW5jaWVzX21ldGFkYXRhLnByb3RvEgRsZW5zIsYECiFMZW5zT3ZlcmxheVBoYXNlTGF0ZW5jaWVzTWV0YWRhdGESPAoFcGhhc2UYASADKAsyLS5sZW5zLkxlbnNPdmVybGF5UGhhc2VMYXRlbmNpZXNNZXRhZGF0YS5QaGFzZRqrAwoFUGhhc2USYAoUaW1hZ2VfZG93bnNjYWxlX2RhdGEYAyABKAsyQC5sZW5zLkxlbnNPdmVybGF5UGhhc2VMYXRlbmNpZXNNZXRhZGF0YS5QaGFzZS5JbWFnZURvd25zY2FsZURhdGFIABJaChFpbWFnZV9lbmNvZGVfZGF0YRgEIAEoCzI9LmxlbnMuTGVuc092ZXJsYXlQaGFzZUxhdGVuY2llc01ldGFkYXRhLlBoYXNlLkltYWdlRW5jb2RlRGF0YUgAGlAKEkltYWdlRG93bnNjYWxlRGF0YRIbChNvcmlnaW5hbF9pbWFnZV9zaXplGAEgASgDEh0KFWRvd25zY2FsZWRfaW1hZ2Vfc2l6ZRgCIAEoAxqDAQoPSW1hZ2VFbmNvZGVEYXRhEk4KE29yaWdpbmFsX2ltYWdlX3R5cGUYASABKA4yMS5sZW5zLkxlbnNPdmVybGF5UGhhc2VMYXRlbmNpZXNNZXRhZGF0YS5JbWFnZVR5cGUSIAoYZW5jb2RlZF9pbWFnZV9zaXplX2J5dGVzGAIgASgDQgwKCnBoYXNlX2RhdGEiNQoJSW1hZ2VUeXBlEgsKB1VOS05PV04QABIICgRKUEVHEAESBwoDUE5HEAISCAoEV0VCUBADYgZwcm90bzM");

/**
 * Describes the message lens.LensOverlayPhaseLatenciesMetadata.
 * Use `create(LensOverlayPhaseLatenciesMetadataSchema)` to create a new message.
 */
export const LensOverlayPhaseLatenciesMetadataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_phase_latencies_metadata, 0);

/**
 * Describes the message lens.LensOverlayPhaseLatenciesMetadata.Phase.
 * Use `create(LensOverlayPhaseLatenciesMetadata_PhaseSchema)` to create a new message.
 */
export const LensOverlayPhaseLatenciesMetadata_PhaseSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_phase_latencies_metadata, 0, 0);

/**
 * Describes the message lens.LensOverlayPhaseLatenciesMetadata.Phase.ImageDownscaleData.
 * Use `create(LensOverlayPhaseLatenciesMetadata_Phase_ImageDownscaleDataSchema)` to create a new message.
 */
export const LensOverlayPhaseLatenciesMetadata_Phase_ImageDownscaleDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_phase_latencies_metadata, 0, 0, 0);

/**
 * Describes the message lens.LensOverlayPhaseLatenciesMetadata.Phase.ImageEncodeData.
 * Use `create(LensOverlayPhaseLatenciesMetadata_Phase_ImageEncodeDataSchema)` to create a new message.
 */
export const LensOverlayPhaseLatenciesMetadata_Phase_ImageEncodeDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_phase_latencies_metadata, 0, 0, 1);

/**
 * Describes the enum lens.LensOverlayPhaseLatenciesMetadata.ImageType.
 */
export const LensOverlayPhaseLatenciesMetadata_ImageTypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_phase_latencies_metadata, 0, 0);

/**
 * @generated from enum lens.LensOverlayPhaseLatenciesMetadata.ImageType
 */
export const LensOverlayPhaseLatenciesMetadata_ImageType = /*@__PURE__*/
  tsEnum(LensOverlayPhaseLatenciesMetadata_ImageTypeSchema);

