// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_cluster_info.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_routing_info } from "./lens_overlay_routing_info_pb.js";

/**
 * Describes the file lens_overlay_cluster_info.proto.
 */
export const file_lens_overlay_cluster_info = /*@__PURE__*/
  fileDesc("Ch9sZW5zX292ZXJsYXlfY2x1c3Rlcl9pbmZvLnByb3RvEgRsZW5zIoIBChZMZW5zT3ZlcmxheUNsdXN0ZXJJbmZvEhkKEXNlcnZlcl9zZXNzaW9uX2lkGAEgASgJEhkKEXNlYXJjaF9zZXNzaW9uX2lkGAIgASgJEjIKDHJvdXRpbmdfaW5mbxgGIAEoCzIcLmxlbnMuTGVuc092ZXJsYXlSb3V0aW5nSW5mb2IGcHJvdG8z", [file_lens_overlay_routing_info]);

/**
 * Describes the message lens.LensOverlayClusterInfo.
 * Use `create(LensOverlayClusterInfoSchema)` to create a new message.
 */
export const LensOverlayClusterInfoSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_cluster_info, 0);

