// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_server.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_client_logs } from "./lens_overlay_client_logs_pb.js";
import { file_lens_overlay_routing_info } from "./lens_overlay_routing_info_pb.js";
import { file_lens_overlay_service_deps } from "./lens_overlay_service_deps_pb.js";

/**
 * Describes the file lens_overlay_server.proto.
 */
export const file_lens_overlay_server = /*@__PURE__*/
  fileDesc("ChlsZW5zX292ZXJsYXlfc2VydmVyLnByb3RvEgRsZW5zIkcKI0xlbnNPdmVybGF5U2VydmVyQ2x1c3RlckluZm9SZXF1ZXN0EiAKGGVuYWJsZV9zZWFyY2hfc2Vzc2lvbl9pZBgBIAEoCCKQAQokTGVuc092ZXJsYXlTZXJ2ZXJDbHVzdGVySW5mb1Jlc3BvbnNlEhkKEXNlcnZlcl9zZXNzaW9uX2lkGAEgASgJEhkKEXNlYXJjaF9zZXNzaW9uX2lkGAIgASgJEjIKDHJvdXRpbmdfaW5mbxgDIAEoCzIcLmxlbnMuTGVuc092ZXJsYXlSb3V0aW5nSW5mbyKIAQoWTGVuc092ZXJsYXlTZXJ2ZXJFcnJvchI6CgplcnJvcl90eXBlGAEgASgOMiYubGVucy5MZW5zT3ZlcmxheVNlcnZlckVycm9yLkVycm9yVHlwZSIyCglFcnJvclR5cGUSEAoMVU5LTk9XTl9UWVBFEAASEwoPTUlTU0lOR19SRVFVRVNUEAEiyAEKGExlbnNPdmVybGF5U2VydmVyUmVxdWVzdBI4Cg9vYmplY3RzX3JlcXVlc3QYASABKAsyHy5sZW5zLkxlbnNPdmVybGF5T2JqZWN0c1JlcXVlc3QSQAoTaW50ZXJhY3Rpb25fcmVxdWVzdBgCIAEoCzIjLmxlbnMuTGVuc092ZXJsYXlJbnRlcmFjdGlvblJlcXVlc3QSMAoLY2xpZW50X2xvZ3MYAyABKAsyGy5sZW5zLkxlbnNPdmVybGF5Q2xpZW50TG9ncyLIAQoZTGVuc092ZXJsYXlTZXJ2ZXJSZXNwb25zZRIrCgVlcnJvchgBIAEoCzIcLmxlbnMuTGVuc092ZXJsYXlTZXJ2ZXJFcnJvchI6ChBvYmplY3RzX3Jlc3BvbnNlGAIgASgLMiAubGVucy5MZW5zT3ZlcmxheU9iamVjdHNSZXNwb25zZRJCChRpbnRlcmFjdGlvbl9yZXNwb25zZRgDIAEoCzIkLmxlbnMuTGVuc092ZXJsYXlJbnRlcmFjdGlvblJlc3BvbnNlYgZwcm90bzM", [file_lens_overlay_client_logs, file_lens_overlay_routing_info, file_lens_overlay_service_deps]);

/**
 * Describes the message lens.LensOverlayServerClusterInfoRequest.
 * Use `create(LensOverlayServerClusterInfoRequestSchema)` to create a new message.
 */
export const LensOverlayServerClusterInfoRequestSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_server, 0);

/**
 * Describes the message lens.LensOverlayServerClusterInfoResponse.
 * Use `create(LensOverlayServerClusterInfoResponseSchema)` to create a new message.
 */
export const LensOverlayServerClusterInfoResponseSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_server, 1);

/**
 * Describes the message lens.LensOverlayServerError.
 * Use `create(LensOverlayServerErrorSchema)` to create a new message.
 */
export const LensOverlayServerErrorSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_server, 2);

/**
 * Describes the enum lens.LensOverlayServerError.ErrorType.
 */
export const LensOverlayServerError_ErrorTypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_server, 2, 0);

/**
 * @generated from enum lens.LensOverlayServerError.ErrorType
 */
export const LensOverlayServerError_ErrorType = /*@__PURE__*/
  tsEnum(LensOverlayServerError_ErrorTypeSchema);

/**
 * Describes the message lens.LensOverlayServerRequest.
 * Use `create(LensOverlayServerRequestSchema)` to create a new message.
 */
export const LensOverlayServerRequestSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_server, 3);

/**
 * Describes the message lens.LensOverlayServerResponse.
 * Use `create(LensOverlayServerResponseSchema)` to create a new message.
 */
export const LensOverlayServerResponseSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_server, 4);

