// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_image_crop.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_geometry } from "./lens_overlay_geometry_pb.js";
import { file_lens_overlay_payload } from "./lens_overlay_payload_pb.js";

/**
 * Describes the file lens_overlay_image_crop.proto.
 */
export const file_lens_overlay_image_crop = /*@__PURE__*/
  fileDesc("Ch1sZW5zX292ZXJsYXlfaW1hZ2VfY3JvcC5wcm90bxIEbGVucyJlCglJbWFnZUNyb3ASDwoHY3JvcF9pZBgBIAEoCRIgCgVpbWFnZRgCIAEoCzIRLmxlbnMuQ2xpZW50SW1hZ2USJQoLem9vbWVkX2Nyb3AYAyABKAsyEC5sZW5zLlpvb21lZENyb3BiBnByb3RvMw", [file_lens_overlay_geometry, file_lens_overlay_payload]);

/**
 * Describes the message lens.ImageCrop.
 * Use `create(ImageCropSchema)` to create a new message.
 */
export const ImageCropSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_image_crop, 0);

