// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_client_context.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_filters } from "./lens_overlay_filters_pb.js";
import { file_lens_overlay_platform } from "./lens_overlay_platform_pb.js";
import { file_lens_overlay_surface } from "./lens_overlay_surface_pb.js";

/**
 * Describes the file lens_overlay_client_context.proto.
 */
export const file_lens_overlay_client_context = /*@__PURE__*/
  fileDesc("CiFsZW5zX292ZXJsYXlfY2xpZW50X2NvbnRleHQucHJvdG8SBGxlbnMisAIKGExlbnNPdmVybGF5Q2xpZW50Q29udGV4dBIgCghwbGF0Zm9ybRgBIAEoDjIOLmxlbnMuUGxhdGZvcm0SHgoHc3VyZmFjZRgCIAEoDjINLmxlbnMuU3VyZmFjZRIrCg5sb2NhbGVfY29udGV4dBgEIAEoCzITLmxlbnMuTG9jYWxlQ29udGV4dBIOCgZhcHBfaWQYBiABKAkSLAoOY2xpZW50X2ZpbHRlcnMYESABKAsyFC5sZW5zLkFwcGxpZWRGaWx0ZXJzEjEKEXJlbmRlcmluZ19jb250ZXh0GBQgASgLMhYubGVucy5SZW5kZXJpbmdDb250ZXh0EjQKE2NsaWVudF9sb2dnaW5nX2RhdGEYFyABKAsyFy5sZW5zLkNsaWVudExvZ2dpbmdEYXRhIkQKDUxvY2FsZUNvbnRleHQSEAoIbGFuZ3VhZ2UYASABKAkSDgoGcmVnaW9uGAIgASgJEhEKCXRpbWVfem9uZRgDIAEoCSJRChBSZW5kZXJpbmdDb250ZXh0Ej0KFXJlbmRlcmluZ19lbnZpcm9ubWVudBgCIAEoDjIeLmxlbnMuTGVuc1JlbmRlcmluZ0Vudmlyb25tZW50IjAKEUNsaWVudExvZ2dpbmdEYXRhEhsKE2lzX2hpc3RvcnlfZWxpZ2libGUYASABKAgqWQoYTGVuc1JlbmRlcmluZ0Vudmlyb25tZW50Eh0KGVJFTkRFUklOR19FTlZfVU5TUEVDSUZJRUQQABIeChpSRU5ERVJJTkdfRU5WX0xFTlNfT1ZFUkxBWRAOYgZwcm90bzM", [file_lens_overlay_filters, file_lens_overlay_platform, file_lens_overlay_surface]);

/**
 * Describes the message lens.LensOverlayClientContext.
 * Use `create(LensOverlayClientContextSchema)` to create a new message.
 */
export const LensOverlayClientContextSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_client_context, 0);

/**
 * Describes the message lens.LocaleContext.
 * Use `create(LocaleContextSchema)` to create a new message.
 */
export const LocaleContextSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_client_context, 1);

/**
 * Describes the message lens.RenderingContext.
 * Use `create(RenderingContextSchema)` to create a new message.
 */
export const RenderingContextSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_client_context, 2);

/**
 * Describes the message lens.ClientLoggingData.
 * Use `create(ClientLoggingDataSchema)` to create a new message.
 */
export const ClientLoggingDataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_client_context, 3);

/**
 * Describes the enum lens.LensRenderingEnvironment.
 */
export const LensRenderingEnvironmentSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_client_context, 0);

/**
 * @generated from enum lens.LensRenderingEnvironment
 */
export const LensRenderingEnvironment = /*@__PURE__*/
  tsEnum(LensRenderingEnvironmentSchema);

