// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_platform.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_platform.proto.
 */
export const file_lens_overlay_platform = /*@__PURE__*/
  fileDesc("ChtsZW5zX292ZXJsYXlfcGxhdGZvcm0ucHJvdG8SBGxlbnMqUQoIUGxhdGZvcm0SGAoUUExBVEZPUk1fVU5TUEVDSUZJRUQQABIQCgxQTEFURk9STV9XRUIQAxIZChVQTEFURk9STV9MRU5TX09WRVJMQVkQBmIGcHJvdG8z");

/**
 * Describes the enum lens.Platform.
 */
export const PlatformSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_platform, 0);

/**
 * @generated from enum lens.Platform
 */
export const Platform = /*@__PURE__*/
  tsEnum(PlatformSchema);

