// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_knowledge_intent_query.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_translate_stickiness_signals } from "./lens_overlay_translate_stickiness_signals_pb.js";

/**
 * Describes the file lens_overlay_knowledge_intent_query.proto.
 */
export const file_lens_overlay_knowledge_intent_query = /*@__PURE__*/
  fileDesc("CilsZW5zX292ZXJsYXlfa25vd2xlZGdlX2ludGVudF9xdWVyeS5wcm90bxIEbGVucyJqCgxGdW5jdGlvbkNhbGwSDAoEbmFtZRgBIAEoCRIgCghhcmd1bWVudBgCIAMoCzIOLmxlbnMuQXJndW1lbnQSKgoHc2lnbmFscxgEIAEoCzIZLmxlbnMuRnVuY3Rpb25DYWxsU2lnbmFscyJhChNGdW5jdGlvbkNhbGxTaWduYWxzEkoKHHRyYW5zbGF0ZV9zdGlja2luZXNzX3NpZ25hbHMY5oG9lAEgASgLMiAubGVucy5UcmFuc2xhdGVTdGlja2luZXNzU2lnbmFscyI8CghBcmd1bWVudBIMCgRuYW1lGAEgASgJEiIKBXZhbHVlGAIgASgLMhMubGVucy5Bcmd1bWVudFZhbHVlIkMKDUFyZ3VtZW50VmFsdWUSKQoMc2ltcGxlX3ZhbHVlGAMgASgLMhEubGVucy5TaW1wbGVWYWx1ZUgAQgcKBXZhbHVlIi4KC1NpbXBsZVZhbHVlEhYKDHN0cmluZ192YWx1ZRgBIAEoCUgAQgcKBXZhbHVlYgZwcm90bzM", [file_lens_overlay_translate_stickiness_signals]);

/**
 * Describes the message lens.FunctionCall.
 * Use `create(FunctionCallSchema)` to create a new message.
 */
export const FunctionCallSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_knowledge_intent_query, 0);

/**
 * Describes the message lens.FunctionCallSignals.
 * Use `create(FunctionCallSignalsSchema)` to create a new message.
 */
export const FunctionCallSignalsSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_knowledge_intent_query, 1);

/**
 * Describes the message lens.Argument.
 * Use `create(ArgumentSchema)` to create a new message.
 */
export const ArgumentSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_knowledge_intent_query, 2);

/**
 * Describes the message lens.ArgumentValue.
 * Use `create(ArgumentValueSchema)` to create a new message.
 */
export const ArgumentValueSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_knowledge_intent_query, 3);

/**
 * Describes the message lens.SimpleValue.
 * Use `create(SimpleValueSchema)` to create a new message.
 */
export const SimpleValueSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_knowledge_intent_query, 4);

