// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_payload.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_payload.proto.
 */
export const file_lens_overlay_payload = /*@__PURE__*/
  fileDesc("ChpsZW5zX292ZXJsYXlfcGF5bG9hZC5wcm90bxIEbGVucyIkCgtDbGllbnRJbWFnZRIVCg1pbWFnZV9jb250ZW50GAEgASgMYgZwcm90bzM");

/**
 * Describes the message lens.ClientImage.
 * Use `create(ClientImageSchema)` to create a new message.
 */
export const ClientImageSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_payload, 0);

