// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_client_logs.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_phase_latencies_metadata } from "./lens_overlay_phase_latencies_metadata_pb.js";

/**
 * Describes the file lens_overlay_client_logs.proto.
 */
export const file_lens_overlay_client_logs = /*@__PURE__*/
  fileDesc("Ch5sZW5zX292ZXJsYXlfY2xpZW50X2xvZ3MucHJvdG8SBGxlbnMi8wMKFUxlbnNPdmVybGF5Q2xpZW50TG9ncxJJChhwaGFzZV9sYXRlbmNpZXNfbWV0YWRhdGEYASABKAsyJy5sZW5zLkxlbnNPdmVybGF5UGhhc2VMYXRlbmNpZXNNZXRhZGF0YRJYChhsZW5zX292ZXJsYXlfZW50cnlfcG9pbnQYAiABKA4yMS5sZW5zLkxlbnNPdmVybGF5Q2xpZW50TG9ncy5MZW5zT3ZlcmxheUVudHJ5UG9pbnRIAIgBARIWCglwYWVsbGFfaWQYAyABKARIAYgBARIoChttZXRyaWNzX2NvbGxlY3Rpb25fZGlzYWJsZWQYBSABKAhIAogBASKnAQoVTGVuc092ZXJsYXlFbnRyeVBvaW50EhcKE1VOS05PV05fRU5UUllfUE9JTlQQABIMCghBUFBfTUVOVRABEhUKEVBBR0VfQ09OVEVYVF9NRU5VEAISFgoSSU1BR0VfQ09OVEVYVF9NRU5VEAMSEgoOT01OSUJPWF9CVVRUT04QBBISCg5UT09MQkFSX0JVVFRPThAFEhAKDEZJTkRfSU5fUEFHRRAGQhsKGV9sZW5zX292ZXJsYXlfZW50cnlfcG9pbnRCDAoKX3BhZWxsYV9pZEIeChxfbWV0cmljc19jb2xsZWN0aW9uX2Rpc2FibGVkYgZwcm90bzM", [file_lens_overlay_phase_latencies_metadata]);

/**
 * Describes the message lens.LensOverlayClientLogs.
 * Use `create(LensOverlayClientLogsSchema)` to create a new message.
 */
export const LensOverlayClientLogsSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_client_logs, 0);

/**
 * Describes the enum lens.LensOverlayClientLogs.LensOverlayEntryPoint.
 */
export const LensOverlayClientLogs_LensOverlayEntryPointSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_client_logs, 0, 0);

/**
 * @generated from enum lens.LensOverlayClientLogs.LensOverlayEntryPoint
 */
export const LensOverlayClientLogs_LensOverlayEntryPoint = /*@__PURE__*/
  tsEnum(LensOverlayClientLogs_LensOverlayEntryPointSchema);

