// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_text_query.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_text_query.proto.
 */
export const file_lens_overlay_text_query = /*@__PURE__*/
  fileDesc("Ch1sZW5zX292ZXJsYXlfdGV4dF9xdWVyeS5wcm90bxIEbGVucyIuCglUZXh0UXVlcnkSDQoFcXVlcnkYASABKAkSEgoKaXNfcHJpbWFyeRgCIAEoCGIGcHJvdG8z");

/**
 * Describes the message lens.TextQuery.
 * Use `create(TextQuerySchema)` to create a new message.
 */
export const TextQuerySchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_text_query, 0);

