// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_surface.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_surface.proto.
 */
export const file_lens_overlay_surface = /*@__PURE__*/
  fileDesc("ChpsZW5zX292ZXJsYXlfc3VyZmFjZS5wcm90bxIEbGVucypSCgdTdXJmYWNlEhcKE1NVUkZBQ0VfVU5TUEVDSUZJRUQQABIUChBTVVJGQUNFX0NIUk9NSVVNEAQSGAoUU1VSRkFDRV9MRU5TX09WRVJMQVkQKmIGcHJvdG8z");

/**
 * Describes the enum lens.Surface.
 */
export const SurfaceSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_surface, 0);

/**
 * @generated from enum lens.Surface
 */
export const Surface = /*@__PURE__*/
  tsEnum(SurfaceSchema);

