// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_filters.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_filters.proto.
 */
export const file_lens_overlay_filters = /*@__PURE__*/
  fileDesc("ChpsZW5zX292ZXJsYXlfZmlsdGVycy5wcm90bxIEbGVucyLGAQoNQXBwbGllZEZpbHRlchIwCgtmaWx0ZXJfdHlwZRgBIAEoDjIbLmxlbnMuTGVuc092ZXJsYXlGaWx0ZXJUeXBlEjIKCXRyYW5zbGF0ZRgDIAEoCzIdLmxlbnMuQXBwbGllZEZpbHRlci5UcmFuc2xhdGVIABo9CglUcmFuc2xhdGUSFwoPdGFyZ2V0X2xhbmd1YWdlGAEgASgJEhcKD3NvdXJjZV9sYW5ndWFnZRgCIAEoCUIQCg5maWx0ZXJfcGF5bG9hZCI1Cg5BcHBsaWVkRmlsdGVycxIjCgZmaWx0ZXIYASADKAsyEy5sZW5zLkFwcGxpZWRGaWx0ZXIqUAoVTGVuc092ZXJsYXlGaWx0ZXJUeXBlEhcKE1VOS05PV05fRklMVEVSX1RZUEUQABINCglUUkFOU0xBVEUQAhIPCgtBVVRPX0ZJTFRFUhAHYgZwcm90bzM");

/**
 * Describes the message lens.AppliedFilter.
 * Use `create(AppliedFilterSchema)` to create a new message.
 */
export const AppliedFilterSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_filters, 0);

/**
 * Describes the message lens.AppliedFilter.Translate.
 * Use `create(AppliedFilter_TranslateSchema)` to create a new message.
 */
export const AppliedFilter_TranslateSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_filters, 0, 0);

/**
 * Describes the message lens.AppliedFilters.
 * Use `create(AppliedFiltersSchema)` to create a new message.
 */
export const AppliedFiltersSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_filters, 1);

/**
 * Describes the enum lens.LensOverlayFilterType.
 */
export const LensOverlayFilterTypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_filters, 0);

/**
 * @generated from enum lens.LensOverlayFilterType
 */
export const LensOverlayFilterType = /*@__PURE__*/
  tsEnum(LensOverlayFilterTypeSchema);

