// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_interaction_request_metadata.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_geometry } from "./lens_overlay_geometry_pb.js";
import { file_lens_overlay_text_query } from "./lens_overlay_text_query_pb.js";

/**
 * Describes the file lens_overlay_interaction_request_metadata.proto.
 */
export const file_lens_overlay_interaction_request_metadata = /*@__PURE__*/
  fileDesc("Ci9sZW5zX292ZXJsYXlfaW50ZXJhY3Rpb25fcmVxdWVzdF9tZXRhZGF0YS5wcm90bxIEbGVucyKtBwolTGVuc092ZXJsYXlJbnRlcmFjdGlvblJlcXVlc3RNZXRhZGF0YRI+CgR0eXBlGAEgASgOMjAubGVucy5MZW5zT3ZlcmxheUludGVyYWN0aW9uUmVxdWVzdE1ldGFkYXRhLlR5cGUSWQoSc2VsZWN0aW9uX21ldGFkYXRhGAIgASgLMj0ubGVucy5MZW5zT3ZlcmxheUludGVyYWN0aW9uUmVxdWVzdE1ldGFkYXRhLlNlbGVjdGlvbk1ldGFkYXRhElEKDnF1ZXJ5X21ldGFkYXRhGAQgASgLMjkubGVucy5MZW5zT3ZlcmxheUludGVyYWN0aW9uUmVxdWVzdE1ldGFkYXRhLlF1ZXJ5TWV0YWRhdGEatgMKEVNlbGVjdGlvbk1ldGFkYXRhElQKBXBvaW50GAEgASgLMkMubGVucy5MZW5zT3ZlcmxheUludGVyYWN0aW9uUmVxdWVzdE1ldGFkYXRhLlNlbGVjdGlvbk1ldGFkYXRhLlBvaW50SAASVgoGcmVnaW9uGAIgASgLMkQubGVucy5MZW5zT3ZlcmxheUludGVyYWN0aW9uUmVxdWVzdE1ldGFkYXRhLlNlbGVjdGlvbk1ldGFkYXRhLlJlZ2lvbkgAElYKBm9iamVjdBgDIAEoCzJELmxlbnMuTGVuc092ZXJsYXlJbnRlcmFjdGlvblJlcXVlc3RNZXRhZGF0YS5TZWxlY3Rpb25NZXRhZGF0YS5PYmplY3RIABodCgVQb2ludBIJCgF4GAEgASgCEgkKAXkYAiABKAIaMAoGUmVnaW9uEiYKBnJlZ2lvbhgBIAEoCzIWLmxlbnMuQ2VudGVyUm90YXRlZEJveBo9CgZPYmplY3QSEQoJb2JqZWN0X2lkGAEgASgJEiAKCGdlb21ldHJ5GAIgASgLMg4ubGVucy5HZW9tZXRyeUILCglzZWxlY3Rpb24aNAoNUXVlcnlNZXRhZGF0YRIjCgp0ZXh0X3F1ZXJ5GAIgASgLMg8ubGVucy5UZXh0UXVlcnkipgEKBFR5cGUSCwoHVU5LTk9XThAAEgcKA1RBUBABEgoKBlJFR0lPThACEhIKDlRFWFRfU0VMRUNUSU9OEAMSEQoNUkVHSU9OX1NFQVJDSBAEEhYKEk9CSkVDVF9GVUxGSUxMTUVOVBAFEhsKF0NPTlRFWFRVQUxfU0VBUkNIX1FVRVJZEAkSDQoJUERGX1FVRVJZEAoSEQoNV0VCUEFHRV9RVUVSWRALYgZwcm90bzM", [file_lens_overlay_geometry, file_lens_overlay_text_query]);

/**
 * Describes the message lens.LensOverlayInteractionRequestMetadata.
 * Use `create(LensOverlayInteractionRequestMetadataSchema)` to create a new message.
 */
export const LensOverlayInteractionRequestMetadataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_interaction_request_metadata, 0);

/**
 * Describes the message lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.
 * Use `create(LensOverlayInteractionRequestMetadata_SelectionMetadataSchema)` to create a new message.
 */
export const LensOverlayInteractionRequestMetadata_SelectionMetadataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_interaction_request_metadata, 0, 0);

/**
 * Describes the message lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.Point.
 * Use `create(LensOverlayInteractionRequestMetadata_SelectionMetadata_PointSchema)` to create a new message.
 */
export const LensOverlayInteractionRequestMetadata_SelectionMetadata_PointSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_interaction_request_metadata, 0, 0, 0);

/**
 * Describes the message lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.Region.
 * Use `create(LensOverlayInteractionRequestMetadata_SelectionMetadata_RegionSchema)` to create a new message.
 */
export const LensOverlayInteractionRequestMetadata_SelectionMetadata_RegionSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_interaction_request_metadata, 0, 0, 1);

/**
 * Describes the message lens.LensOverlayInteractionRequestMetadata.SelectionMetadata.Object.
 * Use `create(LensOverlayInteractionRequestMetadata_SelectionMetadata_ObjectSchema)` to create a new message.
 */
export const LensOverlayInteractionRequestMetadata_SelectionMetadata_ObjectSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_interaction_request_metadata, 0, 0, 2);

/**
 * Describes the message lens.LensOverlayInteractionRequestMetadata.QueryMetadata.
 * Use `create(LensOverlayInteractionRequestMetadata_QueryMetadataSchema)` to create a new message.
 */
export const LensOverlayInteractionRequestMetadata_QueryMetadataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_interaction_request_metadata, 0, 1);

/**
 * Describes the enum lens.LensOverlayInteractionRequestMetadata.Type.
 */
export const LensOverlayInteractionRequestMetadata_TypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_interaction_request_metadata, 0, 0);

/**
 * @generated from enum lens.LensOverlayInteractionRequestMetadata.Type
 */
export const LensOverlayInteractionRequestMetadata_Type = /*@__PURE__*/
  tsEnum(LensOverlayInteractionRequestMetadata_TypeSchema);

