// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_video_params.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_video_context_input_params } from "./lens_overlay_video_context_input_params_pb.js";

/**
 * Describes the file lens_overlay_video_params.proto.
 */
export const file_lens_overlay_video_params = /*@__PURE__*/
  fileDesc("Ch9sZW5zX292ZXJsYXlfdmlkZW9fcGFyYW1zLnByb3RvEgRsZW5zImYKFkxlbnNPdmVybGF5VmlkZW9QYXJhbXMSTAoadmlkZW9fY29udGV4dF9pbnB1dF9wYXJhbXMYASABKAsyKC5sZW5zLkxlbnNPdmVybGF5VmlkZW9Db250ZXh0SW5wdXRQYXJhbXNiBnByb3RvMw", [file_lens_overlay_video_context_input_params]);

/**
 * Describes the message lens.LensOverlayVideoParams.
 * Use `create(LensOverlayVideoParamsSchema)` to create a new message.
 */
export const LensOverlayVideoParamsSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_video_params, 0);

