// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_selection_type.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file lens_overlay_selection_type.proto.
 */
export const file_lens_overlay_selection_type = /*@__PURE__*/
  fileDesc("CiFsZW5zX292ZXJsYXlfc2VsZWN0aW9uX3R5cGUucHJvdG8SBGxlbnMq3QIKGExlbnNPdmVybGF5U2VsZWN0aW9uVHlwZRIaChZVTktOT1dOX1NFTEVDVElPTl9UWVBFEAASEAoMVEFQX09OX0VNUFRZEAESGQoVU0VMRUNUX1RFWFRfSElHSExJR0hUEAMSEQoNUkVHSU9OX1NFQVJDSBAHEhIKDklOSkVDVEVEX0lNQUdFEAoSFwoTVEFQX09OX1JFR0lPTl9HTEVBTRAPEhUKEU1VTFRJTU9EQUxfU0VBUkNIEBISGgoWU0VMRUNUX1RSQU5TTEFURURfVEVYVBAVEhEKDVRBUF9PTl9PQkpFQ1QQFhIgChxNVUxUSU1PREFMX1NVR0dFU1RfVFlQRUFIRUFEEBkSIgoeTVVMVElNT0RBTF9TVUdHRVNUX1pFUk9fUFJFRklYEBoSEgoOVFJBTlNMQVRFX0NISVAQNBIYChRTWU1CT0xJQ19NQVRIX09CSkVDVBA1YgZwcm90bzM");

/**
 * Describes the enum lens.LensOverlaySelectionType.
 */
export const LensOverlaySelectionTypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_selection_type, 0);

/**
 * @generated from enum lens.LensOverlaySelectionType
 */
export const LensOverlaySelectionType = /*@__PURE__*/
  tsEnum(LensOverlaySelectionTypeSchema);

