// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_overlay_object.proto (package lens, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_geometry } from "./lens_overlay_geometry_pb.js";

/**
 * Describes the file lens_overlay_overlay_object.proto.
 */
export const file_lens_overlay_overlay_object = /*@__PURE__*/
  fileDesc("CiFsZW5zX292ZXJsYXlfb3ZlcmxheV9vYmplY3QucHJvdG8SBGxlbnMilAMKDU92ZXJsYXlPYmplY3QSCgoCaWQYASABKAkSIAoIZ2VvbWV0cnkYAiABKAsyDi5sZW5zLkdlb21ldHJ5EkEKEnJlbmRlcmluZ19tZXRhZGF0YRgIIAEoCzIlLmxlbnMuT3ZlcmxheU9iamVjdC5SZW5kZXJpbmdNZXRhZGF0YRJJChZpbnRlcmFjdGlvbl9wcm9wZXJ0aWVzGAQgASgLMikubGVucy5PdmVybGF5T2JqZWN0LkludGVyYWN0aW9uUHJvcGVydGllcxIUCgxpc19mdWxmaWxsZWQYCSABKAgagAEKEVJlbmRlcmluZ01ldGFkYXRhEkUKC3JlbmRlcl90eXBlGAEgASgOMjAubGVucy5PdmVybGF5T2JqZWN0LlJlbmRlcmluZ01ldGFkYXRhLlJlbmRlclR5cGUiJAoKUmVuZGVyVHlwZRILCgdERUZBVUxUEAASCQoFR0xFQU0QARouChVJbnRlcmFjdGlvblByb3BlcnRpZXMSFQoNc2VsZWN0X29uX3RhcBgBIAEoCGIGcHJvdG8z", [file_lens_overlay_geometry]);

/**
 * Describes the message lens.OverlayObject.
 * Use `create(OverlayObjectSchema)` to create a new message.
 */
export const OverlayObjectSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_overlay_object, 0);

/**
 * Describes the message lens.OverlayObject.RenderingMetadata.
 * Use `create(OverlayObject_RenderingMetadataSchema)` to create a new message.
 */
export const OverlayObject_RenderingMetadataSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_overlay_object, 0, 0);

/**
 * Describes the enum lens.OverlayObject.RenderingMetadata.RenderType.
 */
export const OverlayObject_RenderingMetadata_RenderTypeSchema = /*@__PURE__*/
  enumDesc(file_lens_overlay_overlay_object, 0, 0, 0);

/**
 * @generated from enum lens.OverlayObject.RenderingMetadata.RenderType
 */
export const OverlayObject_RenderingMetadata_RenderType = /*@__PURE__*/
  tsEnum(OverlayObject_RenderingMetadata_RenderTypeSchema);

/**
 * Describes the message lens.OverlayObject.InteractionProperties.
 * Use `create(OverlayObject_InteractionPropertiesSchema)` to create a new message.
 */
export const OverlayObject_InteractionPropertiesSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_overlay_object, 0, 1);

