// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_request_id.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_routing_info } from "./lens_overlay_routing_info_pb.js";

/**
 * Describes the file lens_overlay_request_id.proto.
 */
export const file_lens_overlay_request_id = /*@__PURE__*/
  fileDesc("Ch1sZW5zX292ZXJsYXlfcmVxdWVzdF9pZC5wcm90bxIEbGVucyK3AQoUTGVuc092ZXJsYXlSZXF1ZXN0SWQSDAoEdXVpZBgBIAEoBBITCgtzZXF1ZW5jZV9pZBgCIAEoBRIZChFpbWFnZV9zZXF1ZW5jZV9pZBgDIAEoBRIUCgxhbmFseXRpY3NfaWQYBCABKAwSFwoPbG9uZ19jb250ZXh0X2lkGAkgASgFEjIKDHJvdXRpbmdfaW5mbxgGIAEoCzIcLmxlbnMuTGVuc092ZXJsYXlSb3V0aW5nSW5mb2IGcHJvdG8z", [file_lens_overlay_routing_info]);

/**
 * Describes the message lens.LensOverlayRequestId.
 * Use `create(LensOverlayRequestIdSchema)` to create a new message.
 */
export const LensOverlayRequestIdSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_request_id, 0);

