// @generated by protoc-gen-es v2.10.2 with parameter "target=js,import_extension=.js"
// @generated from file lens_overlay_geometry.proto (package lens, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_lens_overlay_polygon } from "./lens_overlay_polygon_pb.js";

/**
 * Describes the file lens_overlay_geometry.proto.
 */
export const file_lens_overlay_geometry = /*@__PURE__*/
  fileDesc("ChtsZW5zX292ZXJsYXlfZ2VvbWV0cnkucHJvdG8SBGxlbnMimAEKEENlbnRlclJvdGF0ZWRCb3gSEAoIY2VudGVyX3gYASABKAISEAoIY2VudGVyX3kYAiABKAISDQoFd2lkdGgYAyABKAISDgoGaGVpZ2h0GAQgASgCEhIKCnJvdGF0aW9uX3oYBSABKAISLQoPY29vcmRpbmF0ZV90eXBlGAYgASgOMhQubGVucy5Db29yZGluYXRlVHlwZSJlCghHZW9tZXRyeRIsCgxib3VuZGluZ19ib3gYASABKAsyFi5sZW5zLkNlbnRlclJvdGF0ZWRCb3gSKwoUc2VnbWVudGF0aW9uX3BvbHlnb24YBSADKAsyDS5sZW5zLlBvbHlnb24ibQoKWm9vbWVkQ3JvcBIkCgRjcm9wGAEgASgLMhYubGVucy5DZW50ZXJSb3RhdGVkQm94EhQKDHBhcmVudF93aWR0aBgCIAEoBRIVCg1wYXJlbnRfaGVpZ2h0GAMgASgFEgwKBHpvb20YBCABKAJiBnByb3RvMw", [file_lens_overlay_polygon]);

/**
 * Describes the message lens.CenterRotatedBox.
 * Use `create(CenterRotatedBoxSchema)` to create a new message.
 */
export const CenterRotatedBoxSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_geometry, 0);

/**
 * Describes the message lens.Geometry.
 * Use `create(GeometrySchema)` to create a new message.
 */
export const GeometrySchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_geometry, 1);

/**
 * Describes the message lens.ZoomedCrop.
 * Use `create(ZoomedCropSchema)` to create a new message.
 */
export const ZoomedCropSchema = /*@__PURE__*/
  messageDesc(file_lens_overlay_geometry, 2);

